#!/bin/bash

QT=$QT_QPA_PLATFORM
XDGC=$XDG_CURRENT_DESKTOP
XDGS=$XDG_SESSION_DESKTOP

export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

flameshot gui

export QT_QPA_PLATFORM=$QT
export XDG_CURRENT_DESKTOP=$XDGC
export XDG_SESSION_DESKTOP=$XDGS



